### ISSUE TITLE
Feature: Be able to adjust clock (time) of the locked screen

### ISSUE THREAD

**Issue by ThanosApostolou** [mate-desktop/mate-screensaver#100]
Even thought I've set my Clock Preferences at 24 hour format, the locked screen shows 12 hour format. The clock panel item and login screen (lightdm greeter) work normally. I asked the question here: https://ubuntu-mate.community/t/locked-screen-shows-12-hour-format-even-if-my-clock-properties-are-set-for-24-hour-format/8619/1 and they told me that the hour format is intergrated into the code. Can you make it adjustable by the clock preferences?
##

**Comment by richwales** [comment]
I managed to fix this by adding the following line to /etc/default/locale:
