### ISSUE TITLE
Background image of lock screen incorrectly stretched

### ISSUE THREAD

**Issue by caringi** [mate-desktop/mate-screensaver#131]
This is not a big issue, but just to let you know...

Starting in MATE 1.18, mate-screensaver is able to  "Lock screen: load user’s background instead of system one"

But in my setup, with 2 monitors, the background image is incorrectly stretched in lock screen.

#### Expected behaviour

Show the background image with correct proportions in lock screen

![fedora rust wallpaper - tux-planet](https://user-images.githubusercontent.com/2509235/27474785-4c730e8e-5803-11e7-83cf-0e6db9926b2d.jpg)

#### Actual behaviour

Background image is incorrectly stretched

![mate_lock_screen](https://user-images.githubusercontent.com/2509235/27474763-37f6f9c0-5803-11e7-8b9d-cde8c9cf3128.png)

#### Steps to reproduce the behaviour

System with 2 monitors, set a background image, lock screen

#### MATE general version

1.18

#### Package version

mate-screensaver-1.18.1-1.fc25.x86_64

#### Linux Distribution

Fedora 25

**Comment by Elnee** [comment]
I have same issue with two monitors on Arch Linux

**Comment by monsta** [comment]
This might be fixed in 1.20.2. Can you check it once more?

**Comment by monsta** [comment]
Ok, got a confirmation in https://github.com/mate-desktop/mate-screensaver/issues/168. Should be fixed in 1.20.2, and I think 1.18.3 solves this too.
