### ISSUE TITLE
hours/minutes text overlaps idle slider

### ISSUE THREAD

**Issue by uelaodi** [mate-desktop/mate-screensaver#135]
#### Expected behaviour
screensaver dialog idle time slider not having text overlap

#### Actual behaviour
the "minutes" and "hours minutes" overlap the idle slider (affects all themes):
![idle-overlap-hours-minutes](https://user-images.githubusercontent.com/30830906/29069790-69c2a780-7c0a-11e7-93c0-621e8fc09c38.png)
![idle-overlap-minutes](https://user-images.githubusercontent.com/30830906/29069785-65493a2a-7c0a-11e7-907d-06eeeaec7ae7.png)

#### MATE general version
1.18.0

#### Package version
1.18.1-1

#### Linux Distribution
Fedora 26

**Comment by raveit65** [comment]
Thanks for reporting but we know already about.
https://github.com/mate-desktop/mate-screensaver/issues/101
