### ISSUE TITLE
Does not unlock

### ISSUE THREAD

**Issue by switzel** [mate-desktop/mate-screensaver#150]
Whenever I lock my screen, mate-screensaver will not accept my password to unlock. Sometimes it works to "switch user" to the same user logged in. Most of the time a switch to a text shell and kill mate-screensaver.

**Comment by lukefromdc** [comment]
What version of MATE, what distro? I recall seeing problems like this especially on resuming from suspend on MATE in Ubuntu a couple years ago, in fact I ended up disabling mate-screensaver entirely on the offending machines

**Comment by fredericmora** [comment]
Happens to me to. I come back to my desktop after a few hours and I see that the screen is sleeping. Keyboard does not respond (e.g., the NumLock key does not light up the keyboard LED). The only solution is to SSH in and kill all the mate processes (and thus my user session).

Running Mate 1.14.1-1+sarah on Mint 18.

**Comment by pyaazkaparatha** [comment]
Are you using conky? I observe this happens sometimes when using conky. Going to next tty and doing "killall conky" re-enables password text field.

**Comment by oz123** [comment]
I can confirm this behavior with mate-screensaver on Gentoo. 
This behavior can be found when building[ mate-screensaver-1.18.2 ](https://gitweb.gentoo.org/proj/gentoo-mate.git/tree/mate-extra/mate-screensaver/mate-screensaver-1.18.2.ebuild) or [1.20.0](https://github.com/oz123/mate-de-gentoo/blob/master/mate-extra/mate-screensaver/mate-screensaver-1.20.1-r1.ebuild).

I am not using conky, or systemd or a finger print reader. My login manager is lightdm.

**Comment by oz123** [comment]
It turns out my issue was wrong pam config together with ecryptfs. If you have an encrypted home partition check your pam config.

**Comment by switzel** [comment]
Please excuse me for not responding. The solution by oz134 works for me, thanks a lot!
