### ISSUE TITLE
lock screen don't read caps lock state at start

### ISSUE THREAD

**Issue by Hybrid512** [mate-desktop/mate-screensaver#151]
It seems mate-screensaver don't reflect the current caps lock state on the lock screen once it is started misleading the user who didn't see that caps are locked.

#### Expected behaviour
If you have caps locked before the screen is locked by mate-screensaver, the should be a notification on the lock screen stating the caps are locked.

#### Actual behaviour
There is no mention that caps are already locked and you type your password with upper cases instead of lower cases.
When pressing the caps lock key, the status is correctly reflected with a notification when caps are locked.

#### Steps to reproduce the behaviour
Press caps lock before lock screen starts

#### MATE general version
1.12

#### Package version
1.12.0-1

#### Linux Distribution
Ubuntu 16.04.4 LTS "xenial"

**Comment by flexiondotorg** [comment]
The is fixed in MATE Screensaver 1.18 and newer but sadly can't be back ported to Ubuntu MATE 16.04.

**Comment by Hybrid512** [comment]
"can't be back ported to Ubuntu MATE 16.04" 

Why so ?

Ubuntu 16.04 is an LTS release and we're using it for our whole remote desktop setup (about 200 users), this is not something we can upgrade easily because we must check every part of our use cases to make sure that everything works as expected (at least, as in the previous release).

This doesn't seem too complicated to fix anyway (can't caps lock state be checked when the locker starts ??)

**Comment by alexarnaud** [comment]
@Hybrid512 Maybe you could try another lock screen that has not this issue on Ubuntu 16.04 ?

Best regards.

**Comment by Hybrid512** [comment]
@monsta : ok, so I understand this is a gtk2 issue ... I'll try to see if it doesn't break too much thing using the MATE Ubuntu Xenial ppa and go with 1.16 instead of 1.12.

@alexarnaud : I tried but found nothing doing exactly what mate-screensaver does (but without the bugs) that don't need to install a whole other desktop such as KDE or XFCE as dependencies.
And no, i3lock is not a solution ... far too "geeky" for my users, I want what mate-screensaver does, no more, no less and not differently.

**Comment by monsta** [comment]
The official PPA with 1.16 is still built with GTK+2. There was no official update to 1.18, the first GTK+3 only release, in order to not break something.

There's an **unofficial** PPA with 1.18 here:
https://launchpad.net/~jonathonf/+archive/ubuntu/mate-1.18

It may or may not work for you. From my experience, 1.18 is known to work fine on Ubuntu 16.04 base. For example, Mint 18.3 is built on that base and has 1.18. But I haven't tested that PPA.

**Comment by monsta** [comment]
As for the screensaver alternative, maybe try light-locker? I think it shouldn't depend on other desktop environments.
