### ISSUE TITLE
[Security] Locker can be bypassed in multi-screen layouts

### ISSUE THREAD

**Issue by phocean** [mate-desktop/mate-screensaver#158]
#### Expected behaviour

The locker is a critical component of the computer security that should not be bypassed in any way.

The screen should remain locked, whatever hardware event may occur.

#### Actual behaviour

Once in a few times, the screen would be unrevealed.

In that case, keyboard entries are ignored, but the mouse can operate at will.
The GUI can be controlled during a few seconds, it seems that there is a timer (~ 15 seconds) until mate-screensaver can lock it back.

I suggest a fix or the possibility for the user to use an alternative and more robust solution.
XFCE somehow offers that, as it looks for several lockers subsequently (including xscreensaver, slock, dm locker, etc.).

#### Steps to reproduce the behaviour

1. Lock the session
2. Plug in and out a few times some external monitor. The issue appears to be more frequent in layout with two external screens (HDMI + Dual port)
3. Once in a few times, the screen would be unrevealed.

In that case, keyboard entries are ignored, but the mouse can operate at will.
The GUI can be controlled during a few seconds, it seems that there is a timer (~ 15 seconds) until mate-screensaver can lock it back.

#### MATE general version

MATE 1.20.1

#### Package version

mate-screensaver 1.20.0

#### Linux Distribution

Ubuntu 18.04 LTS  64-bit

**Comment by sehucke** [comment]
This seems to be a major security issue.

See https://forums.linuxmint.com/viewtopic.php?f=206&t=273611&p=1499700

**Comment by raveit65** [comment]
1.20.2 is released.

**Comment by jeenuv** [comment]
Any idea when the 1.20.2 is going to reach the repositories, or whom to ping? I'm on Mint 19 (Tara), the latest it's got is `1.20.0-1`.

**Comment by raveit65** [comment]
> Any idea when the 1.20.2 is going to reach the repositories, or whom to ping? I'm on Mint 19 (Tara), the latest it's got is 1.20.0-1.

You need to ask your maintainer from linuxmint about, we're are only upstream.
