### ISSUE TITLE
Invisible lock screen when xscreensaver themes used.

### ISSUE THREAD

**Issue by Th30n** [mate-desktop/mate-screensaver#19]
Problem: The lock screen doesn't show up but is active. The screen is black.

OS: Linux Mint 15 (dual booted with Win7 Pro) 64 bit
Versions:
Mate 1.6.0
Mate-Screensaver 1.6.0

Computer: HP 4525s Probook

Steps to reproduce:
- Download xscreensaver themes (I'm using glxscreensaver themes)
- modify themes to show up in mate-screensaver configuration app (modify the line in /usr/share/applications/screensavers/<screensaver_name>.desktop: "OnlyShowIn=GNOME;MATE;")
- select the theme with mate-screensaver-preferences
- choose the option "Lock screen when screensaver is active"
- wait for the screensaver to become active
- move the mouse
- screensaver will stop, the screen will turn black
- the lock window is active but not visible
- type in the password blindly to get back to desktop

**Comment by NiceandGently** [comment]
@Th30n 
Is the issue still exists with Mate-1.8/10 ?

**Comment by Th30n** [comment]
Frankly I have no idea anymore. Since then I've changed the hardware, linux distribution and desktop environments.
On my current setup (detailed below) I am unable to reproduce it.
ArchLinux 64bit, linux kernel 4.0.3-1-ARCH
Mate 1.8.2

**Comment by NiceandGently** [comment]
@Th30n 
Thank you
@stefano-k 
please close, it's not reproducible anymore
