### ISSUE TITLE
can't access issue

### ISSUE THREAD

**Issue by bressucli2** [mate-desktop/mate-screensaver#196]
greetings,

i created an issue last night and github said it was hidden from the public (fine; i could still see it and i presume those with privileges on this project could, too), but now i'm also locked out of my original account and so am unable to view or update the issue.

could the admin of mate-screensaver make the original issue (https://github.com/mate-desktop/mate-screensaver/issues/195) public so i can see and post to the issue with my new account? or if that's not possible, can you copy the issue report here and close/remove the original issue?

thanks and sorry for the noise :-/

**Comment by sc0w** [comment]
github says me: **Page not found**

**Comment by bressucli2** [comment]
@sc0w -- thanks for checking ... I've created a new issue: https://github.com/mate-desktop/mate-screensaver/issues/197
