### ISSUE TITLE
libXxf86misc dependency becomes deprecated

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/mate-screensaver#199]
#### Expected behaviour
Building package with libXxf86misc dependency in fedora 31 (next release in October /November)

#### Actual behaviour
libXxf86misc dependency can't be satisfied in fedora 31

#### Steps to reproduce the behaviour
Complie package in fedora rawhide (f31)

#### MATE general version
All

#### Package version
All

#### Linux Distribution
Fedora, probably other will follow bleeding edge leader

#### Link to downstream report of your Distribution
Not reported, things needs to be clarified before i file out a report against libXxf86misc.
Latest version of libXxf86misc in fedora.
https://koji.fedoraproject.org/koji/buildinfo?buildID=1291079

Comment from Xorg developer:
```
Stop building the devel subpackage in Fedora and RHEL > 8,
no new code should try to use this library,
the X server hasn't implemented it in over 10 years
```
In result i have to build mate-settings-demon, mate-screensaver and mate-control-center without it.
I have no idea about the consequences.
Does anyone know for what libXxf86misc is used?
Or better for what we use it in mate-screensaver?

@mate-desktop/contributors @mate-desktop/core-team @mate-desktop/documentation-team 
Any idea?

**Comment by lukefromdc** [comment]
I cannot even FIND this package in Debian Unstable, is it included in something else here, or an optional dependency that does not get built?
