### ISSUE TITLE
mate-panel visible on background dialog popup with compiz

### ISSUE THREAD

**Issue by fdsky** [mate-desktop/mate-screensaver#216]
#### Expected behaviour
Desktop should remain hidden regardless of X and compiz activity in the background. 

#### Actual behaviour
mate-panel becomes visible, though not clickable on background dialog popup. Tested and does not occur with marco or compton.

#### Steps to reproduce the behaviour
With compiz running as your compositor, on the lockscreen, invoke a dialog in the background. Insert a luks drive that caja will pop up a passphrase dialog for, xmessage yourself, anything that will cause a pop-up - mate-panel will appear.

#### MATE general version
1.22.2

#### Package version
mate-screensaver 1.22.2-2
compiz 2:0.8.16.1-12

#### Dist
Sid

**Comment by lukefromdc** [comment]
I was unable to confirm this on mate-screensaver 1.23.1 from git master current as of Dec 19,2019

**Comment by fdsky** [comment]
> I was unable to confirm this on mate-screensaver 1.23.1 from git master current as of Dec 19,2019
> EDIT: test was inserting an audio CD with Caja set to ask what to do, and inserting the CD with the screen locked. Mate-panel did not become visible. WM is compiz-reloaded from my branch, which differs from git master only in that I have modified gtk-window-decorator to support hidpi and am using a 4K monitor.
> 
> Don't know if my setup or my mate-screensaver version is what is making the difference here.

You're right, I just installed 1.23.1 and it doesn't happen. This bug must have been patched and just hasn't reached the sid repo just yet. Thanks for testing @lukefromdc

**Comment by lukefromdc** [comment]
1.23 won't go to Sid, but will eventually become 1.24. If the commit that changed this can be identified it could possibly be backported
