### ISSUE TITLE
GNOME Floating Feets .svg file is expired edition??

### ISSUE THREAD

**Issue by esteelpaz** [mate-desktop/mate-screensaver#232]
#### Expected behaviour
I anticipate that when the screensaver kicks in I will see the GNOME Floating Feets "bubbling" around my display.

#### Actual behaviour
Instead I get an emptiness of black.

#### Steps to reproduce the behaviour
Problem happened in May '20 and the U-MATE forum provided a new .svg file for the GNOME foot and that fixed the problem in my then three MATE distros.  Last week I noticed in my two OpenSUSE Tumbleweed MATE distros and my new LM MATE 20 distro that the Floating Feets were again "gone" . . . but in the U-MATE and also my Manjaro MATE distros still had the Floating Feets??

I again replaced the old .svg with a copy of the newer one that U-MATE provided me on the three broken screensavers and again I had the Feets!!!
I filed a bug report on Launchpad, but I don't anticipate a flurry of activity as it likely is related to mate-screensaver and how it is accessing the "pixmaps" directory?    https://bugzilla.opensuse.org/show_bug.cgi?id=1176426

#### MATE general version
I couldn't find that data in TW

#### Package version
current

#### Linux Distribution
OpenSUSE TW, Gecko, and LM 20 Ulyana

#### Link to downstream report of your Distribution
??

**Comment by mbkma** [comment]
It is already fixed in master: https://github.com/mate-desktop/mate-screensaver/pull/226 and backported to 1.24.1. Hence, distributions which upgraded MATE packages to 1.24.1 will have the fix available, others may not.

**Comment by esteelpaz** [comment]
Great!!  And, yes, I recently did a fresh install of Leap 15.3 that I then added the MATE pattern to, and the Floating Feets screensaver was operational without having to replace the .svg file and so forth.

**Comment by mbkma** [comment]
Cool! Could you close this and the other bugreports please, since #226 fixed the problem.

**Comment by esteelpaz** [comment]
OK, I will close this one, since I opened it.  But, at the time, almost one year ago now #226 didn't actually "fix" the problem in the downstream playpen . . . even a few months back I had to go through the replace .svg file procedure.  It was only last week where I noticed that I didn't have to do anything to "fix" the problem--other stuff going on right now.
