### ISSUE TITLE
crash core dump

### ISSUE THREAD

**Issue by secpoint** [mate-desktop/mate-screensaver#236]
#### Actual behaviour

coredump 
#### Steps to reproduce the behaviour
https://termbin.com/qtkp

#### MATE general version
20

**Comment by rbuj** [comment]
Do not use links to insecure pages from a secure page.

> #### Steps to reproduce the behaviour
> https://termbin.com/qtkp
>

**Comment by rbuj** [comment]
Writing part of the description to an external server such as pastebin makes it difficult to trace and track the issue, please use the markdown language to attach the reverse trace as a code block or attach a text file directly.
