### ISSUE TITLE
Mate 1.26 screensaver/logout fails

### ISSUE THREAD

**Issue by bob-10598** [mate-desktop/mate-screensaver#263]
#### Expected behaviour
Lock screen icon on menu bar starts screensaver

#### Actual behaviour
screensaver aborts

#### Steps to reproduce the behaviour
Update 1.24 to 1.26
Click lockscreen icon copy on panel

#### MATE general version
1.26

#### Linux Distribution
Fedora 34

#### Link to bugreport of your Distribution (requirement)
https://bugzilla.redhat.com/show_bug.cgi?id=1997852

**Comment by ProMarbler14** [comment]
With https://github.com/mate-desktop/mate-screensaver/pull/262 , the issue appears to be fixed; the screensaver runs normally without any black screen or crash.

**Comment by raveit65** [comment]
> To reproduce:
> 
>     1. (start mate-screensaver)
> 
>     2. (as root) `cp /usr/share/applications/mate-panel.desktop /usr/share/applications/TMPTMPTMP.desktop; rm /usr/share/applications/TMPTMPTMP.desktop`
> 
>     3. `mate-screensaver-command -a`
> 
With that steps to reproduce i can confirm the issue now, and it doesn't matter whether mate-menus is build with
`mate-menus_0001-Revert-matemenu-tree-do-not-call-g_settings_get_stri.patch`
`mate-menus_0001-Let-user-disable-collection-menu-entry-disable-colle.patch`
`--disable-collection`
or from 1.26.0 release.
Luckily https://github.com/mate-desktop/mate-screensaver/pull/262 seems to fis the issue.

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/mate-screensaver/pull/262 seems to fix this for me too
