### ISSUE TITLE
[Enhancement on missing package called 'autoconf-archive' request]

### ISSUE THREAD

**Issue by rubyFeedback** [mate-desktop/mate-screensaver#265]
Hey mate-desktop folks,

I can compile almost all of mate-desktop from source. \o/

I currently have a problem with mate-screensaver, though.

It says:

"configure: error: You need to install the autoconf-archive package."

Is plain old GNU autoconf meant with this? Aka

https://ftp.gnu.org/pub/gnu/autoconf/autoconf-2.71.tar.xz

If so I have it installed but mate-screensaver still complains.

Or is a special mate-package meant? In this case please
show the name or tarball release.

(Perhaps it may be best to transition into meson in
the long run. GNU configure is such a mess ... but this
is a separate aspect, in this issue here I am only
curious to find out which autoconf package is meant
exactly. The regular autoconf above I have
compiled and installed with prefix /usr/ so I am
unsure why mate-screensaver complains.
The other mate components compile fine by the
way.)

**Comment by rbuj** [comment]
You can learn more about the GNU Autoconf Archive at https://www.gnu.org/software/autoconf-archive/
