### ISSUE TITLE
Cannot remove 'Background picture for lock screen:'

### ISSUE THREAD

**Issue by HectorB-2020** [mate-desktop/mate-screensaver#269]
#### Expected behaviour
There must be some way of removing previously chosen file
in the field "**Background picture for lock screen:'**"
dialog "**Screensaver Preferences**".

#### Actual behaviour
Once a file has been selected, there are no obvious ways of removing that file name.

#### Steps to reproduce the behaviour
Open dialog "**Screensaver Preferences**". Click on "**Background picture for lock screen:**", select a file.

#### MATE general version
1.26

#### Package version
1.26

#### Linux Distribution
Ubuntu 21.10 with latest updates.

#### Link to bugreport of your Distribution (requirement)
https://bugs.launchpad.net/ubuntu/+source/mate-screensaver/+bug/1955340

**Comment by N0rbert** [comment]
Please please fill "Link to bugreport of your Distribution (requirement)" field.
