### ISSUE TITLE
Css for lock screen

### ISSUE THREAD

**Issue by luigifab** [mate-desktop/mate-screensaver#271]
This is a question, how I can set styles (from my theme) for the lock screen in Mate 1.26?
The gtk-inspector doesn't start, so I can't find css class names.

![lock-screen](https://user-images.githubusercontent.com/31816829/147411459-6b2679a9-0ab6-4421-89ab-9c49715ca78f.png)

**Comment by rbuj** [comment]
https://github.com/mate-desktop/mate-screensaver/blob/bc818733fbbd96a3de36f800d567e54009cc0630/data/lock-dialog-default.ui#L15

**Comment by raveit65** [comment]
Take a look at our themes, ie. blue-submarine https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/Blue-Submarine/gtk-3.0/mate-applications.css#L1302
css selector is `.lock-dialog`

**Comment by luigifab** [comment]
So nice, thank you very much!
