### ISSUE TITLE
Feature request: Show the lock-delay setting in the GUI

### ISSUE THREAD

**Issue by davidhedlund** [mate-desktop/mate-screensaver#282]
#### Expected behaviour
Should lock itself when the screenssaver is turned on.

#### Actual behaviour
Does not lock itself when the screenssaver is turned on.

#### Steps to reproduce the behaviour
Open mate-screensaver-preferences (Settings > System > Preferences > Look and Feel > Screensaver)
* "Lock screen when screensaver is active" is already enabled

# Test 1
* Set "Regard the computer as idle after:" to 1 minute
* Idle until the screensaver gets fully activated, then move the mouse pointer after: 45 seconds (set a timer). The lock screen doesn't show up.
* Idle until the screensaver gets fully activated, then move the mouse pointer after: 60 seconds (set a timer). The lock screen shows up.

# Test 2
* Set "Regard the computer as idle after:" to 2 minutes
* Idle until the screensaver gets fully activated, then move the mouse pointer after: 45 seconds (set a timer). The lock screen doesn't show up.
* Idle until the screensaver gets fully activated, then move the mouse pointer after: 60 seconds (set a timer). The lock screen shows up.

#### MATE general version
Multiple

#### Package version
See https://bugs.launchpad.net/ubuntu/+source/mate-screensaver/+bug/2017879 where I first filed it.

#### Linux Distribution
Debian, Ubuntu, Ubuntu MATE, etc. See https://bugs.launchpad.net/ubuntu/+source/mate-screensaver/+bug/2017879 where I first filed it.

#### Link to bugreport of your Distribution (requirement)
https://bugs.launchpad.net/ubuntu/+source/mate-screensaver/+bug/2017879

**Comment by zhuyaliang** [comment]
gsettings set org.mate.screensaver lock-delay 0
```
    <key name="lock-delay" type="i">
      <default>0</default>
      <summary>Time before locking</summary>
      <description>The number of minutes after screensaver activation before locking the screen.</description>
    </key>
```

**Comment by davidhedlund** [comment]
> gsettings set org.mate.screensaver lock-delay 0
> 
> ```
>     <key name="lock-delay" type="i">
>       <default>0</default>
>       <summary>Time before locking</summary>
>       <description>The number of minutes after screensaver activation before locking the screen.</description>
>     </key>
> ```

Thank you very much. That's why the delay is 60 seconds for me:

```
gsettings get org.mate.screensaver lock-delay
1
```

* I guess that the lock delay should be set to 0?
* Also, there's no lock delay setting for the screensaver in the GUI:
![image](https://github.com/mate-desktop/mate-screensaver/assets/6416073/4ef9be81-c634-40ce-a4e7-d6b98714973c)

**Comment by zhuyaliang** [comment]
> I guess that the lock delay should be set to 0?

The default is 0, it should be because other configurations have modified ```lock-delay```, using ```grep -rin lock-delay/usr/share/glib-2.0/schemas/```

> Also, there's no lock delay setting for the screensaver in the GUI:

At present, lock delay can only be set through ```gsettings set org.date.screensave lock-delay 0```

**Comment by davidhedlund** [comment]
> > I guess that the lock delay should be set to 0?
> 
> The default is 0, it should be because other configurations have modified `lock-delay`, using `grep -rin lock-delay/usr/share/glib-2.0/schemas/`
> 
You've been very helpful! This is set to `1`, on Ubuntu, I filed an issue for the distro.

> > Also, there's no lock delay setting for the screensaver in the GUI:
> 
> At present, lock delay can only be set through `gsettings set org.date.screensave lock-delay 0`

For security reasons, I think this should be visible in the GUI. I change the title once again to solely focus on this.

**Comment by davidhedlund** [comment]
> > I guess that the lock delay should be set to 0?
> 
> The default is 0, it should be because other configurations have modified `lock-delay`, using `grep -rin lock-delay/usr/share/glib-2.0/schemas/`
> 
> > Also, there's no lock delay setting for the screensaver in the GUI:
> 
> At present, lock delay can only be set through `gsettings set org.date.screensave lock-delay 0`

grep -rin "lock-delay=1" /usr/share/glib-2.0/schemas/
/usr/share/glib-2.0/schemas/10_mate-common.gschema.override:92:lock-delay=1

**Comment by davidhedlund** [comment]
* https://github.com/mate-desktop/mate-screensaver/issues/287
