### ISSUE TITLE
[GTK3] saver does not start immediately

### ISSUE THREAD

**Issue by infirit** [mate-desktop/mate-screensaver#37]
Settings, idle time 1 minute and lock screen enabled. You can reproduce it with either waiting for it to start after a minute or issuing mate-screensaver-command --lock.

With gtk2 the saver starts immediately. And only when I move the mouse/hit a key the unlock window shows.

With gtk3, this is reversed. It shows me the unlock window not the saver. I do see the saver if I wait for a bit or hit the cancel button on the unlock window.

afaics there is nothing logged.

**Comment by NiceandGently** [comment]
@infirit 
@flexiondotorg 
This is fixed since a long time, please close it
