### ISSUE TITLE
mate-screensaver-command --poke does not work

### ISSUE THREAD

**Issue by theothercliff** [mate-desktop/mate-screensaver#4]
simple test case:
1 - set the mate screen saver timeout to 1 minute (system>preferences>screensaver, "Regard the computer as idle after:" slider set all the way to the left = 1 minute) for this testing to avoid the long wait.
2 - in mate-terminal (bash command line) execute the following command that waits for 63 seconds then pokes the screen saver to simulate user activity; as soon as you press the return key on the command, avoid touching the keyboard or mouse for at least 65 seconds

          while true; do sleep 58; mate-screensaver-command --poke; echo -n poked...; done

What you get is that every 58 seconds, "poked..." gets printed, but the screensaver activates at 60 seconds.  The poking should have reset the screensaver timeout so that the screensaver should not activate.

The equivalent command in Ubuntu Gnome 10.10:

          while true; do sleep 58; gnome-screensaver-command --poke; echo -n poked...; done

works as expected and keeps the screensaver from activating.

You can change the time to 63 seconds.  In Ubuntu Gnome, you see the screen begin to noticeably dim and then come back to full brightness the instant it gets poked.  In Mint Mate the screen dims and blanks out, but before it goes completely black, you see that "poked..." gets printed, but it didn't help.

**Comment by NiceandGently** [comment]
For me any  sleep > 60 works as expected with mate-1.10.
@theothercliff 
can you reproduce the issue with updated mate?

**Comment by raveit65** [comment]
no answer from reporter!
