### ISSUE TITLE
Clock in lockscreen not in 24 hours mode

### ISSUE THREAD

**Issue by LouisDK1** [mate-desktop/mate-screensaver#48]
I've installed MATE 1.8.1 on Arch Linux and my clock is set to 24 hours mode, however the lockscreen it doesn't respect this and shows 9:49 if my system time is set to 21:49.

It would be nice if the lockscreen was able to show the clock based on system settings.

**Comment by ZaxonXP** [comment]
Is there a way to set the 24h clock format from the command line or by editing some config file?
