### ISSUE TITLE
SMPlayer not working with screensaver

### ISSUE THREAD

**Issue by philipzae** [mate-desktop/mate-screensaver#66]
I use smplayer as my default video player and noticed that when it is in the paused state, mate-screensaver doesnt start. I filed a bug report with smplayer (https://sourceforge.net/p/smplayer/bugs/670/) and the developer stated "SMPlayer just passes the option -stop-xscreensaver to mplayer, so mplayer handles the screensaver." I was wondering if mate-screensaver is intercepting this or whether this is a problem with mplayer.

**Comment by monsta** [comment]
Should work now with 1.12. We now use gnome's names on DBus, and video players should (hopefully) recognize them. Please test it.

**Comment by philipzae** [comment]
Works correctly with mpv but wasnt able to test mplayer or mplayer2 as there arent any new versions available in the trusty repo that contains the necessary patch that enables the '-xscreensaver-when-paused' commandline switch ( https://trac.mplayerhq.hu/ticket/2229 ). Hopefully its fixed in 16.04's build of mplayer and mplayer2.

**Comment by monsta** [comment]
You can always test newer distros in VMs :smile:

**Comment by philipzae** [comment]
Unfortunately my system crashes when using Virtualbox and my system cant run the latest VMWare and Virtual Machine Manager runs to slow. :(

**Comment by monsta** [comment]
Ok, so does it happen in 16.04?

**Comment by philipzae** [comment]
16.04 has switched back from mplayer2 to mplayer, so it should be fixed.
