### ISSUE TITLE
Ubuntu 15.10 Mate alpha screen saver will not unlock

### ISSUE THREAD

**Issue by cigtoxdoc** [mate-desktop/mate-screensaver#73]
Ubuntu 15.10 Mate alpha screensaver will not unlock with user password.  Have to remove lock from screensaver to have functioning PC

**Comment by infirit** [comment]
Works for me in a VM. Open the logs (dmesg and xsession-error come to mind) and look for errors.

Also works fine on my main gentoo machine.

@flexiondotorg fyi

**Comment by flexiondotorg** [comment]
@sunweaver Perhaps the patch discussed here is relevant?

**Comment by flexiondotorg** [comment]
@cigtoxdoc I can confirm this issue in Ubuntu MATE 15.10. My work around is to use Switch User in the lock screen and then authenticate as the same user because this doesn't destroy the session ☺

**Comment by flexiondotorg** [comment]
Also tagging @monsta so he is aware for future Mint releases.

**Comment by usdanskys** [comment]
@flexiondotorg I can confirm your work-around

**Comment by raveit65** [comment]
Please check you logs if the fprintd daemon is running, more infos here
https://bugzilla.redhat.com/show_bug.cgi?id=984333#c23
This is one possible cause of the issue.

**Comment by monsta** [comment]
@flexiondotorg: unlocking works fine for me in current 15.10, so if @raveit65 confirms the same in Fedora, I think this can be closed.

**Comment by flexiondotorg** [comment]
This is indeed fixed for sometime.

**Comment by raveit65** [comment]
I'm not shure about, see rhbz report.
M-s has a code that if ie. fprind daemon is active the lock-screen change to sensitive.
I could reproduce that for some reason the fprintd daemon systemd unit was started by another service or app, which is wrong on a hardware w/o fingerprint hardware.
But reporter said that fprintd isn't installed on his system.
Resposible for this behaviour is this g-s commit which is also in in m-s.
https://git.gnome.org/browse/gnome-screensaver/commit/?id=ce391d2167ab1f5a11ca457630cc3221ab1abc53
So, i guess that sometimes another service trigger this code line and you can't type a password.
So, i'm not really thinking this is fixed.

**Comment by usdanskys** [comment]
Ubuntu 15.10 with no fprintd; unlocking works properly.

**Comment by monsta** [comment]
Yes, I don't remember fprintd being in Ubuntu... so maybe it's a separate bug?

**Comment by raveit65** [comment]
If you think that running fprintd on hardware w/o hardware for it, cause m-s lockscreen to sensitive is a seperate bug, what is the cause of this bug ;)
For me the problem are those code lines
https://github.com/mate-desktop/mate-screensaver/blob/master/src/gs-lock-plug.c#L1589
https://github.com/mate-desktop/mate-screensaver/blob/master/src/gs-lock-plug.c#L1613

**Comment by monsta** [comment]
Just installed fprintd in Ubuntu 15.10 VM and started fprintd with -t option ("Do not exit after unused for a while").
No problems with unlocking.
