### ISSUE TITLE
Lock screen caps lock alert doesn't appear if already on

### ISSUE THREAD

**Issue by chrstphrchvz** [mate-desktop/mate-screensaver#81]
The notice that appears when caps lock becomes activated while typing the password to unlock (e.g. after suspend, screensaver) isn't shown if the lock screen is displayed while caps lock is already activated (toggling caps lock off then on will still display it). This is a minor inconvenience where caps lock is usually warned if on; i.e. I expect the notice to already be present when the lock screen appears if the caps lock is on, and that the state of caps lock is always reflected by the presence or absence of the alert.
(tested on mate-screensaver 1.8.1-2 and 1.10.2-1, Ubuntu MATE 15.04 amd64)
##

**Comment by sc0w** [comment]
This is fixed in gnome-screensaver

We need find the commit and adapt it to mate-screensaver

**Comment by sc0w** [comment]
I had that problem in 1.12 gtk2

With 1.14 gtk3 it works

**Comment by flexiondotorg** [comment]
I patch is land for GTK2+ in Ubuntu Xenial and Yakkety.

  * https://bugs.launchpad.net/bugs/1576424

With the patch to explicitly disconnect keymap signals applied to GTK2+, the Caps notification behaviour is identical on the GTK2+ and GTK3+ builds.

But, the behaviour is wrong. The Caps notification is only displayed while the key is depressed, not while caps lock is active.

**Comment by monsta** [comment]
Indeed, this doesn't happen with GTK+3, so it's time to close it.
