### ISSUE TITLE
c/

### ISSUE THREAD

**Issue by iWildStyle** [mate-desktop/mate-screensaver#85]

**Comment by raveit65** [comment]
????
closed.

**Comment by iWildStyle** [comment]
Oops. Sorry. Stupid very sensitive touchpad.
30 окт. 2015 г. 16:02 пользователь "Wolfgang Ulbrich" <
notifications@github.com> написал:

**Comment by raveit65** [comment]
@flexiondotorg 
????

**Comment by flexiondotorg** [comment]
Sorry, thought I read this was closed by mistake.
