### ISSUE TITLE
'man mate-screensaver-command' opens mate-screensaver's manpage

### ISSUE THREAD

**Issue by drws** [mate-desktop/mate-screensaver#94]
The title says what the whole problem is. I'm running fairly recent version of mate-desktop (1.12.1) with mate-screensaver 1.12.0 and when I type `man mate-screensaver-command` the same manpage as if I ran `man mate-screensaver` appears (containing a reference to mate-screensaver-command(1)!).
##

**Comment by monsta** [comment]
Thanks for spotting it - looks like an old copy-paste mistake from https://github.com/mate-desktop/mate-screensaver/commit/9075047d57bfdde4419ce37e043a23ec5691bf2b.
