### ISSUE TITLE
in xmonad tiling window manager, only locks a window instead of the entire screen

### ISSUE THREAD

**Issue by installe** [mate-desktop/mate-screensaver#96]
I'm using mate with xmonad as window manager.
Since a recent upgrade (to debian package version 1.14.1-1), mate-screensaver creates a window, which displays as one of the tiles on the screen, instead of taking up the entire screen.

When using mate-screensaver to lock the screen, the keyboard is locked, but the mouse isn't, so it's still possible to interact with applications running in the other tiles that are displayed next to mate-screensaver. This is a security issue. It is also a regression, as in previous versions it used to lock the entire screen.
##

**Comment by robbertkrebbers** [comment]
This bug no longer appears when using the last version of mate-screensaver (commit dd83748). So, it was probably a bug in mate-screensaver, and not in xmonad.

**Comment by raveit65** [comment]
So we can close this report here?

**Comment by robbertkrebbers** [comment]
Geekosaur wrote the following in [my xmonad bug report](https://github.com/xmonad/xmonad/issues/40):

> But yes, a screensaver must use override-redirect, otherwise it is not taking full control like a screensaver must to ensure security. If xmonad was seeing the window at all, they weren't using override-redirect.

It would be good to know that mate-screensaver is indeed doing this, and the bug has not disappeared because of some other quirk.

**Comment by monsta** [comment]
Can you do ```git bisect``` to pinpoint the commit that possibly fixed it?
